spring:
profiles: production
datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/myapp}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
jpa:
    hibernate:
    ddl-auto: validate
    show-sql: false
