spring:
    jpa:
        show-sql: true       # вывод SQL-запросов
#    main:
#        banner-mode: "off"
    output:
        ansi:
            enabled: always    # цветной вывод логотипа

# В application.yml
logging:
    pattern:
        dateformat: "yyyy-MM-dd HH:mm:ss"  # кастомный формат даты в логах
    console:
        color-enabled: true

app:
    welcome-message: "Welcome to Spring blog!"  # наше кастомное сообщение
    admin-email: admin-email@gmail.com
    page-size: 8