spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver   # общий драйвер (будет переопределен для prod)

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      format_sql: true
      ddl-auto: update

  main:
    banner-mode: "off"   # Banner off
  output:
    ansi:
      enabled: ALWAYS } }

# src/main/resources/certs/
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem


# В application.yml
logging:
  level:
    #root: WARN
    org:
      springframework:
        # web: DEBUG
        #security: DEBUG
pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"  # кастомный формат даты в логах
  #console:
  #  color-enabled: true

app:
  welcome-message: "Welcome to Spring blog!"  # наше кастомное сообщение
  admin-email: admin-email@gmail.com
  page-size: 8
  fixedTime: "2025-08-08T23:00"